name = "tg-image"
main = "src/worker/index.ts"
compatibility_date = "2026-06-10"
compatibility_flags = ["nodejs_compat"]


keep_vars = true

[[d1_databases]]
binding = "DATABASE"
database_name = "tg-image-db"
database_id = "5f042add-2054-4080-8868-281f50015d8e"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[triggers]
crons = ["0 2 * * *"]