name = "tg-image"
main = "src/worker/index.ts"
compatibility_date = "2026-06-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DATABASE"
database_name = "tg-image-db"
database_id = "5f042add-2054-4080-8868-281f50015d8e"

[vars]
DOMAIN = "img.example.com"
ENABLE_AUTH = "false"
MAX_SIZE_MB = "20"

[triggers]
crons = ["0 2 * * *"]