name: Sync to Sub-Account

于:
  push:
    branches:
      - main  # 如果大号是 master，请改成 master

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the HTTP repository
        uses: s0/git-publish-action@main
        env:
          REMOTE_URL: "https://github.com/xi118/Telegraph-image.git"
          API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
