name: Sync to Sub-Account

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the HTTP repository
        uses: s0/git-publish-action@main
        env:
          REMOTE_URL: "https://github.com/xi118/Telegraph-image.git"
          API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
